/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graphtutorial;

import org.junit.Test;

import controller.App;

import static org.junit.Assert.*;

public class StartTest {
    @Test public void appHasAGreeting() {
        App appTest = new App();
		appTest.setUp();
    }
}
